Converting PH assets to UIImage
hhunaid/react-native-image-crop-tools pull request #19
Opened 2020-11-20 06:27 UTC by priyankachoudhary221614

2020-11-20 12:18 UTC, hhunaid commented on ios/RCTCropView.m
> +    TOCropView * _inlineCropView, * url;
url should be an NSString instance. And by the looks of it, it can be a local var instead of an instance member.

2020-11-20 12:19 UTC, hhunaid commented on ios/RCTCropView.m
> +    if([sourceUrl rangeOfString:@"ph://"].location == 0) {
This if clause should be moved up to line 21.

2020-11-20 12:19 UTC, hhunaid commented on ios/RCTCropView.h
> +@property (nonatomic, strong) PHImageRequestOptions * requestOptions;
This does not need to be a public property

2020-11-20 12:20 UTC, hhunaid requested changes
Thank you very much for the PR. Please address the comments if you can.

2020-11-22 15:37 UTC, priyankachoudhary221614 commented
> Thank you very much for the PR. Please address the comments if you can.

I have addressed your comments. Please check.

2020-11-22 23:13 UTC, merged

2020-11-23 06:25 UTC, priyankachoudhary221614 commented
Hello, Can you tell me when the new version will be released?